Repository Oneflow-Inc/vision, pull requests merged in 2022-01, with the labels that each got.

#102 Dev add change log
  README.md
  docs/source/changelog.md
  docs/source/index.rst
  projects/classification/main.py
Labels: Priority: 0, Improvements

#103 Revise Doc
  flowvision/data/mixup.py
  flowvision/data/random_erasing.py
  flowvision/models/_utils.py
  flowvision/models/alexnet.py
  flowvision/models/conv_mixer.py
  flowvision/models/crossformer.py
  flowvision/models/cswin.py
  flowvision/models/densenet.py
  flowvision/models/efficientnet.py
  flowvision/models/ghostnet.py
  flowvision/models/googlenet.py
  flowvision/models/inception_v3.py
  flowvision/models/mlp_mixer.py
  flowvision/models/mnasnet.py
  flowvision/models/mobilenet_v2.py
  flowvision/models/mobilenet_v3.py
  flowvision/models/neural_style_transfer/stylenet.py
  flowvision/models/pvt.py
  flowvision/models/res2net.py
  flowvision/models/res_mlp.py
  flowvision/models/resnet.py
  flowvision/models/rexnet.py
  flowvision/models/rexnet_lite.py
  flowvision/models/shufflenet_v2.py
  flowvision/models/squeezenet.py
  flowvision/models/swin_transformer.py
  flowvision/models/utils.py
  flowvision/models/vgg.py
  flowvision/models/vit.py
Labels: Priority: 0, Improvements

#106 [Draft] add numpy normalize implementation
  flowvision/data/transforms_factory.py
  flowvision/transforms/functional.py
Labels: Priority: 0, Improvements

#111 remove flow.utils.vision
  flowvision/datasets/coco.py
  flowvision/datasets/folder.py
  flowvision/transforms/functional.py
  flowvision/transforms/transforms.py
Labels: Priority: 0, Bug Fixes

#112 refine
  flowvision/datasets/folder.py
  flowvision/transforms/functional.py
  projects/benchmark/classification/benchmark.py
Labels: Priority: 0, Bug Fixes

#100 Support linspace and trunc_normal
  docs/source/changelog.md
  flowvision/models/crossformer.py
  flowvision/models/cswin.py
  flowvision/models/pvt.py
  flowvision/models/swin_transformer.py
  projects/benchmark/classification/eval.sh
Labels: New Features, Priority: 0, Bug Fixes

#114 Update requirements.txt
  docs/requirements.txt
Labels: bug, documentation

#119 Sphinx document list collapse
  docs/source/_static/collapse.js_t
  docs/source/_static/css/sidebar.css
  docs/source/_templates/layout.html
  docs/source/conf.py
Labels: documentation, Priority: 0, Improvements

#122 Fix network bug
  docs/source/changelog.md
  docs/source/conf.py
  flowvision/models/crossformer.py
  flowvision/models/cswin.py
  flowvision/models/efficientnet.py
  flowvision/models/pvt.py
  flowvision/models/res2net.py
  flowvision/models/swin_transformer.py
Labels: Bug Fixes

#115 Rebuild vision transformer model
  docs/source/changelog.md
  docs/source/flowvision.models.rst
  flowvision/models/__init__.py
  flowvision/models/helpers.py
  flowvision/models/mlp_mixer.py
  flowvision/models/utils.py
  flowvision/models/vision_transformer.py
  flowvision/models/vit.py
  projects/benchmark/classification/eval.sh
Labels: New Features, Priority: 0, Improvements

#85 Add scheduler
  docs/source/changelog.md
  flowvision/scheduler/__init__.py
  flowvision/scheduler/poly_lr.py
  flowvision/scheduler/tanh_lr.py
Labels: New Features, Priority: 1

#123 add __repr__ and model_list in ModelCreator
  docs/source/changelog.md
  flowvision/models/registry.py
Labels: Priority: 1, Improvements

#117 Add speed test script
  ci/check/compare_speed_with_pytorch.py
  ci/check/run_speed_test.sh
  docs/requirements.txt
  flowvision/layers/regularization/stochastic_depth.py
  flowvision/models/crossformer.py
  flowvision/models/ghostnet.py
  flowvision/models/mlp_mixer.py
  flowvision/models/mobilenet_v2.py
  flowvision/models/mobilenet_v3.py
  flowvision/models/pvt.py
  flowvision/models/res_mlp.py
  flowvision/models/rexnet_lite.py
  flowvision/models/swin_transformer.py
  flowvision/models/vision_transformer.py
Labels: Priority: 0, Improvements, Bug Fixes

#125 release v0.0.6
  README.md
  docs/requirements.txt
  setup.py
Labels: New Features

#110 delete flowvision.models._util
  flowvision/models/detection/backbone_utils.py
  flowvision/models/layer_getter.py
Labels: Priority: 1, Improvements

#127 Update flowvision download func
  docs/source/changelog.md
  flowvision/models/utils.py
Labels: Priority: 0, Improvements

#128 Rebuild MODEL_ZOO
  MODEL_SUMMARY.md
  MODEL_ZOO.md
  README.md
  docs/source/changelog.md
  docs/source/flowvision.models.rst
  flowvision/models/alexnet.py
  flowvision/models/densenet.py
  flowvision/models/res2net.py
  flowvision/models/res_mlp.py
  flowvision/models/vgg.py
  flowvision/models/vision_transformer.py
  projects/benchmark/classification/benchmark.py
  projects/benchmark/classification/eval.sh
  results/results_imagenet.md
Labels: Priority: 0, Improvements, Bug Fixes

#130 fix coco dataset mask type
  projects/detection/coco_utils.py
Labels: Bug Fixes
