Repository Oneflow-Inc/vision, pull requests merged in 2022-02, with the labels that each got.

#93 Support ConvNeXt
  docs/source/changelog.md
  docs/source/flowvision.models.rst
  flowvision/models/__init__.py
  flowvision/models/convnext.py
  projects/benchmark/classification/eval.sh
  results/results_imagenet.md
Labels: New Features, Priority: 0

#132 add rexnet-lite weights
  README.md
  docs/source/changelog.md
  docs/source/tutorials/Getting Started.md
  flowvision/models/rexnet_lite.py
  projects/benchmark/classification/eval.sh
  results/results_imagenet.md
Labels: New Features, Priority: 0

#133 Fix import error
  docs/source/flowvision.layers.rst
  flowvision/layers/__init__.py
  flowvision/layers/attention/bam.py
  flowvision/layers/attention/cbam.py
  flowvision/layers/attention/coordatt.py
  flowvision/layers/attention/global_context.py
  flowvision/layers/attention/non_local_attn.py
  flowvision/layers/blocks/__init__.py
  flowvision/layers/helpers.py
  flowvision/models/convnext.py
  flowvision/models/crossformer.py
  flowvision/models/cswin.py
  flowvision/models/efficientnet.py
  flowvision/models/ghostnet.py
  flowvision/models/mlp_mixer.py
  flowvision/models/mobilenet_v2.py
  flowvision/models/mobilenet_v3.py
  flowvision/models/pvt.py
  flowvision/models/res_mlp.py
  flowvision/models/rexnet_lite.py
  flowvision/models/swin_transformer.py
  flowvision/models/vision_transformer.py
  projects/benchmark/classification/eval.sh
Labels: Priority: 0, Improvements

#143 simplify the description of SE
  docs/source/flowvision.layers.rst
  flowvision/layers/attention/se.py
Labels: documentation

#152 Update README
  README.md
Labels: documentation, enhancement

#144 add model: regionvit
  README.md
  docs/source/flowvision.models.rst
  flowvision/models/__init__.py
  flowvision/models/regionvit.py
  results/results_imagenet.md
Labels: New Features

#149 Add senet and results docstring
  README.md
  docs/source/flowvision.models.rst
  flowvision/models/__init__.py
  flowvision/models/senet.py
  results/results_imagenet.md
Labels: documentation, enhancement, New Features, Priority: 0

#147 Support UniFormer
  README.md
  ci/check/run_speed_test.sh
  docs/source/flowvision.models.rst
  flowvision/models/__init__.py
  flowvision/models/uniformer.py
  results/results_imagenet.md
Labels: New Features

#156 Add ResNeSt
  .gitignore
  README.md
  ci/check/run_speed_test.sh
  docs/source/flowvision.models.rst
  flowvision/models/__init__.py
  flowvision/models/resnest.py
  results/results_imagenet.md
Labels: New Features

#137 Support Poolformer
  README.md
  ci/check/run_speed_test.sh
  docs/source/flowvision.models.rst
  flowvision/models/__init__.py
  flowvision/models/poolformer.py
  results/results_imagenet.md
Labels: New Features, Priority: 0
