Repository Oneflow-Inc/vision, pull requests merged in 2022-03, with the labels that each got.

#160 Add iresnet
  README.md
  docs/source/changelog.md
  docs/source/flowvision.models.rst
  flowvision/models/__init__.py
  flowvision/models/face_recognition/__init__.py
  flowvision/models/face_recognition/ir_resnet.py
  results/results_insightface_MFR.md
Labels: New Features, Priority: 0

#166 Add Van model
  README.md
  docs/source/changelog.md
  docs/source/flowvision.models.rst
  flowvision/models/__init__.py
  flowvision/models/van.py
  results/results_imagenet.md
Labels: New Features

#171 Add New features： transforms.RandomGrayscale
  docs/source/changelog.md
  docs/source/flowvision.transforms.rst
  flowvision/transforms/__init__.py
  flowvision/transforms/functional.py
  flowvision/transforms/functional_pil.py
  flowvision/transforms/functional_tensor.py
  flowvision/transforms/transforms.py
Labels: New Features

#176 refine docs
  README.md
  docs/source/flowvision.layers.rst
  docs/source/flowvision.loss.rst
  docs/source/flowvision.models.rst
  docs/source/tutorials/Getting Started.md
  flowvision/loss/__init__.py
  flowvision/loss/cross_entropy.py
  flowvision/models/__init__.py
  flowvision/models/detection/faster_rcnn.py
  flowvision/models/detection/retinanet.py
  flowvision/models/detection/ssd.py
  flowvision/models/detection/ssdlite.py
  flowvision/models/face_recognition/ir_resnet.py
  flowvision/models/regnet.py
  flowvision/models/segmentation/deeplabv3.py
  flowvision/models/segmentation/fcn.py
  flowvision/models/segmentation/lraspp.py
  flowvision/models/style_transfer/__init__.py
  flowvision/models/style_transfer/stylenet.py
  flowvision/transforms/functional.py
  flowvision/transforms/functional_pil.py
  flowvision/transforms/functional_tensor.py
  flowvision/transforms/transforms.py
Labels: documentation, Priority: 0

#178 Optimize flowvision docstr sidebar
  docs/source/_static/collapse.js_t
  docs/source/_static/css/sidebar.css
Labels: documentation

#179 Add box iou np impl
  flowvision/layers/blocks/__init__.py
  flowvision/layers/blocks/boxes.py
  flowvision/models/detection/retinanet.py
  flowvision/models/detection/ssd.py
  flowvision/models/detection/transform.py
  projects/detection/train.py
  projects/detection/transforms.py
Labels: bug

#189 Refine Documentation
  docs/source/changelog.md
  docs/source/conf.py
  docs/source/flowvision.data.rst
  docs/source/flowvision.layers.rst
  docs/source/flowvision.models.rst
  docs/source/flowvision.scheduler.rst
  docs/source/flowvision.utils.rst
  flowvision/data/auto_augment.py
  flowvision/data/mixup.py
  flowvision/data/random_erasing.py
  flowvision/loss/cross_entropy.py
  flowvision/scheduler/cosine_lr.py
  flowvision/scheduler/linear_lr.py
  flowvision/scheduler/multistep_lr.py
  flowvision/scheduler/poly_lr.py
  flowvision/scheduler/step_lr.py
  flowvision/utils/clip_grad.py
  flowvision/utils/model_ema.py
  flowvision/utils/vision_helpers.py
Labels: documentation, Priority: 0

#188 Add transforms.GaussianBlur
  docs/source/changelog.md
  docs/source/flowvision.models.rst
  docs/source/flowvision.transforms.rst
  flowvision/models/segmentation/fcn.py
  flowvision/transforms/__init__.py
  flowvision/transforms/functional.py
  flowvision/transforms/functional_tensor.py
  flowvision/transforms/transforms.py
Labels: documentation, New Features, Priority: 0

#192 fix_resume
  flowvision/transforms/functional.py
  flowvision/transforms/functional_tensor.py
  flowvision/transforms/transforms.py
  projects/detection/train.py
Labels: bug

#194 Fix line space
  docs/requirements.txt
  docs/source/_static/collapse.js_t
  docs/source/_static/css/line_space.css
  docs/source/_static/css/sidebar.css
  docs/source/_templates/layout.html
  docs/source/_templates/line_space.html
  docs/source/conf.py
Labels: bug, documentation
